namespace AutoSuggestBoxTextChangeReasonMinRepro
{
    [default_interface]
    runtimeclass SuggestionViewModel : Microsoft.UI.Xaml.Data.INotifyPropertyChanged, Windows.Foundation.IStringable
    {
        SuggestionViewModel(String displayName);
        String DisplayName{ get; };
    }
}
